<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>1.0.7</Version>
    <Authors>Switch Pilot</Authors>
    <Product>Switch Pilot</Product>
    <Company>Switch Pilot</Company>
    <Copyright>Copyright © 2026 Switch Pilot</Copyright>
    <Deterministic>true</Deterministic>
    <DebugType>embedded</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
